# Create a compute instance on OpenStack using Ansible
---
- name: Launch an OpenStack compute instance
  hosts: localhost
  vars_files:    - vars/main.yml
  tasks:
    # Add system to host_group
    # http://docs.ansible.com/ansible/add_host_module.html
    - name: Add system as host
      add_host:
        name: "10.11.53.29:22"
        ansible_ssh_private_key_file: "bastion.pem"
        ansible_user: peon
        ansible_password: peon

    # Wait for port to be opened
    # http://docs.ansible.com/ansible/wait_for_module.html
    - name: Wait for SSH to be active
      local_action: wait_for port="22" host="10.11.53.29" search_regex=OpenSSH


- name: Configure instance withdocker
  hosts: new_hosts #must match groupname in "add_host" above
  vars:
    app_folder: "cloud"
  tasks:
    # Update apt list
    # http://docs.ansible.com/ansible/apt_module.html
    - name: Update apt list
      apt:
        update_cache: yes
      become: true

    # Install APT packages
    - name: Install packages
      apt:
        name: "docker"
      become: true
      with_items:
        - docker-ce

# Launch docker compose
- name: Launch docker
  command: "docker-compose up"
