language: python
python:
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install pytest
  - pip install requests

before_script:
  - docker-compose up -d --scale w=12 --scale b=6
  - sleep 30

script:
  - ./tests/scalabilityPlay.sh
  - pytest

notifications:
  slack:
    secure: g1bL5B4o3GpoGs5LYYGJbekVkGM4xYDSpsHdOaz7A8JMhATlJC2tw3d2sGOfZXIoXS8waOmIAHX/EWyQxZvfTTHMKgszl/F661vn1b1z6nqmetlhDPhyht6735KpODKwXF/KkGtYJyFjqgmyAYcPZQi6a93uiS9ootD0xzb1zlDaudlWfJICN3FpkyHNZMPDkoFZ+p3oaPEgejw7yX+N0GYhMIQmoCoDKLW1WTsaaEi1rCyzCVgwrcZ7bFoxUuBDaTnY6MdhS08BQYPwa3BhhSM6v/msuivw8X6zEcz2FjfEOBxeYZ8DCbAWkM/0Ke4SMXmgFk0meBJJAqYoGHPNGveENRxvqvNc6ufBkZrExA0PqCH0CbeJZF1gKxSB3Fn1Fu0KxajoeWfVaapsJHuEzSI4WqJhKzN4wy9p0mYbAQu5YJ5vUHPpWIFCD4GhkESn0zFul7Up8mAghANEnejqVlz2Rfw+UoGbFVx1Q6yDlSPRv9MDFoiWBls5tx6azicFohG/gIp+MBBawLpZZSFqMytoCnv2AdR25R2ckhfaMx+Fyimp39Y/MfmADvSbgiNPM3UZS31H8N4RdZcPkur2sGwwfQ6QSLX3jAqLVhZcym/RGrmSwITij6yF9J7k6vtvRiP4Eok1adKqQ7L5nxGhjtm/zu4hsK4lc9rNbYbhRCk=
