language: python
python:
  - "2.7"

sudo: required

services:
  - docker

install:
  - pip install pytest

before_script:
  - docker-compose up -d

script:
  - ./tests/scalabilityB.sh
  - ./tests/scalabilityI.sh
  - ./tests/scalabilityP.sh
  - ./tests/scalabilityS.sh
  - ./tests/scalabilityW.sh
  - ./tests/scalabilityPlay.sh
  - pytest
