sudo: required

services:
  - docker

install:
  - pip install pytest

script:
  - ./tests/scalabilityB.sh
  - ./tests/scalabilityI.sh
  - ./tests/scalabilityP.sh
  - ./tests/scalabilityS.sh
  - ./tests/scalabilityW.sh
  - ./tests/scalabilityPlay.sh
  - pytest
