language: python

sudo: required

python:
- '2.7'

env:
- ANSIBLE_HOST_KEY_CHECKING=False

script:
- echo "Run test scripts here"

before_install:
- openssl aes-256-cbc -K $encrypted_d0cfa861f601_key -iv $encrypted_d0cfa861f601_iv -in bastion.pem.enc -out bastion.pem -d
- chmod 600 bastion.pem

before_deploy:
- pip install ansible shade
- apt-get install -y openvpn
- openvpn --config vpnlab2017.conf

deploy:
- provider: script
  script: ansible-playbook .playbook.yml
  on:
    branch: release

addons:
  ssh_known_hosts:
  - 10.11.53.29

notifications:
  slack:
    secure: g1bL5B4o3GpoGs5LYYGJbekVkGM4xYDSpsHdOaz7A8JMhATlJC2tw3d2sGOfZXIoXS8waOmIAHX/EWyQxZvfTTHMKgszl/F661vn1b1z6nqmetlhDPhyht6735KpODKwXF/KkGtYJyFjqgmyAYcPZQi6a93uiS9ootD0xzb1zlDaudlWfJICN3FpkyHNZMPDkoFZ+p3oaPEgejw7yX+N0GYhMIQmoCoDKLW1WTsaaEi1rCyzCVgwrcZ7bFoxUuBDaTnY6MdhS08BQYPwa3BhhSM6v/msuivw8X6zEcz2FjfEOBxeYZ8DCbAWkM/0Ke4SMXmgFk0meBJJAqYoGHPNGveENRxvqvNc6ufBkZrExA0PqCH0CbeJZF1gKxSB3Fn1Fu0KxajoeWfVaapsJHuEzSI4WqJhKzN4wy9p0mYbAQu5YJ5vUHPpWIFCD4GhkESn0zFul7Up8mAghANEnejqVlz2Rfw+UoGbFVx1Q6yDlSPRv9MDFoiWBls5tx6azicFohG/gIp+MBBawLpZZSFqMytoCnv2AdR25R2ckhfaMx+Fyimp39Y/MfmADvSbgiNPM3UZS31H8N4RdZcPkur2sGwwfQ6QSLX3jAqLVhZcym/RGrmSwITij6yF9J7k6vtvRiP4Eok1adKqQ7L5nxGhjtm/zu4hsK4lc9rNbYbhRCk=
